### ISSUE TITLE
Running on VMDK / E01 images

### ISSUE THREAD

**Issue by kartone** [harelsegev/INDXRipper#7]
Other than RAW images, what kind of images (E01/VMDK) are supported? Thanks!

**Comment by harelsegev** [comment]
Only `.raw` images are supported.
Mount your `.vmdk` / `.e01`images using [Arsenal Image Mounter](https://arsenalrecon.com/downloads/), and then run INDXRipper.
ewfmount is also a great option for `.e01`, if you use Linux.

I don't plan on supporting other image formats.
Is there a specific reason mounting is not an option for you?

**Comment by kartone** [comment]
I receive this error with the image mounted via Arsenal

![image](https://user-images.githubusercontent.com/11351872/156810709-f747f142-a798-466b-ba4c-918452aac975.png)

**Comment by harelsegev** [comment]
You should use the device path of the drive.

Try this:
`INDXRipper.exe \\.\J: outfile_1.csv`

**Comment by kartone** [comment]
Thanks!
